### ISSUE TITLE
[BUG] - I CANT JOIN MY WORLD

### ISSUE THREAD

**Issue by ceopet08** [Kikiisyourfriend/ProjectIsothermalExpert#77]
### **Confirm your current modpack version:**

```
1.0.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
my world crash
```

### **Steps to reproduce:**

```
tick erros
```
[crash-2023-04-20_21.17.07-server.txt](https://github.com/Kikiisyourfriend/ProjectIsothermalExpert/files/11289838/crash-2023-04-20_21.17.07-server.txt)

**Comment by itsjusttriz** [comment]
Version 1.0.2 is **not** the latest.

This crash is due to one of your Refined Storage patterns containing an invalid recipe.

What you need to do is revert to a version where this isnt an issue, delete the pattern (*or all the patterns if youre not sure which one is causing the issue*), then re-update to latest modpack version, and recreate the pattern from scratch with the new recipe, from the latest modpack version.

Nothing else can be done about this.

**Comment by ceopet08** [comment]
ok i understand but how I can delete the pattern if I cant join my world?
thanks

**Comment by itsjusttriz** [comment]
> ok i understand but how I can delete the pattern if I cant join my world? thanks

RE-read my msg. I mentioned reverting your instance to a previous version where you CAN join your world... then remove the craft pattern or all of them if you cant find the problematic one... then re-update your instance.. then re-make the craft in the newly updated version.

**Comment by ceopet08** [comment]
oh sorry i didn t understand thank you

**Comment by ceopet08** [comment]
i tried all the day but it doesnt work i don't know what i have to do anymore
